sudo: required

language: scheme

services:
        - docker

before_install:
        - docker pull nkoguro/gauche
        - docker ps -a
        - ps
        - pwd
        - docker run nkoguro/gauche gosh -V
        - docker run nkoguro/gauche sh -c 'mkdir /tmp/Gauche-websocket'
        - docker run -v /home/travis/build/plaster/Gauche-websocket:/tmp/Gauche-websocket nkoguro/gauche gosh -I lib test/parser-test.scm
