sudo: required

language: scheme

services:
        - docker

before_install:
        - docker pull plaster/gauche
        - docker ps -a
        - ps
        - pwd
        - docker run plaster/gauche gosh -V
        - docker run plaster/gauche sh -c 'rm -rf /tmp/Gauche-websocket && mkdir /tmp/Gauche-websocket'

script:
        - docker run -v /home/travis/build/plaster/Gauche-websocket:/tmp/Gauche-websocket plaster/gauche make -C /tmp/Gauche-websocket check
