sudo: required

language: scheme

services:
        - docker

before_install:
        - docker pull nkoguro/gauche
        - docker ps -a
        - ps
        - pwd
        - docker run nkoguro/gauche gosh -I lib test/parser-test.scm
