sudo: required

language: scheme

services:
        - docker

before_install:
        - docker pull nkoguro/gauche:stable
        - docker ps -a
        - ps
        - pwd
        - docker run nkoguro/gauche:stable gosh -V
        - docker run nkoguro/gauche:stable sh -c 'rm -rf /tmp/Gauche-websocket && mkdir /tmp/Gauche-websocket'

script:
        - docker run -v /home/travis/build/plaster/Gauche-websocket:/tmp/Gauche-websocket nkoguro/gauche:stable 'make -C /tmp/Gauche-websocket check > /dev/null'
